
project_id = "xwylatyyhqyfwsxfwzmn"

[api]
enabled = false
port = 54321
schemas = ["public", "storage", "graphql_public"]

[api.headers]
Authorization = "service_role"
apiKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

[analytics]
enabled = false

[db]
port = 54322

[functions]
ensure-storage-bucket = { verify_jwt = false }
create-public-bucket-policy = { verify_jwt = false }

[inbucket]
enabled = false

[studio]
enabled = false

[realtime]
enabled = false

[storage]
enabled = true
