
name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/playback-rental
            git pull origin main
            
            # Install frontend dependencies
            npm install
            
            # Install server dependencies
            cd server
            npm install
            cd ..
            
            # Build frontend
            npm run build
            
            # Copy environment variables if they exist
            if [ -f .env.production ]; then
              cp .env.production .env
            fi
            
            # Restart services with PM2
            pm2 reload ecosystem.config.cjs || pm2 start ecosystem.config.cjs
